# couchdb

couchdbprimary:
  build: roles/couchdb
  volumes:
    - /Users/npmo/couchdb:/usr/local/var/lib/couchdb
  ports:
    - "55984:5984"

# registry

auth:
  container_name: auth
  expose:
    - "5000"
  environment:
    - AUTHENTICATION_METHOD=github
    - AUTHORIZATION_METHOD=github
    - GITHUB_HOST=https://api.github.com
    - GITHUB_ORG=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=github
    - SHARED_FETCH_SECRET=abc123
    - CERTIFICATE=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDRENDQXZDZ0F3SUJBZ0lVSENwS00zaS8xeUZ3TTIzc2lVSEFLcHFTdkJFd0RRWUpLb1pJaHZjTkFRRUYKQlFBd1V6RUxNQWtHQTFVRUJoTUNWVk14RERBS0JnTlZCQW9NQTI1d2JURVZNQk1HQTFVRUN3d01UMjVsVEc5bgphVzRnU1dSUU1SOHdIUVlEVlFRRERCWlBibVZNYjJkcGJpQkJZMk52ZFc1MElEY3lOakEyTUI0WERURTFNVEV4Ck9USXlOVFl4TkZvWERUSXdNVEV5TURJeU5UWXhORm93VXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEREFLQmdOVkJBb00KQTI1d2JURVZNQk1HQTFVRUN3d01UMjVsVEc5bmFXNGdTV1JRTVI4d0hRWURWUVFEREJaUGJtVk1iMmRwYmlCQgpZMk52ZFc1MElEY3lOakEyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5K1ptCkZ4eXlhOUJiRDUrUDJhVG9sSmRIek1ITUZKYXpUcHIyZjhjTklvd1VzYW02eDlrakN2UkFhQXc1ZWMwbjltaHcKVlc0L2h4bWZIZTh1dVJSVnZ3NXpOeXFNMUx6bFZFbndWczVkbmtuclNzQm5kSm9KcG05a1VVL2pPUS9EVlpiOApxamx1YUt6dUoxY3ZqWjZrKzJqU2I3Yyt6QlNJYmsvMGw3Y0IrZTZIKytCRWw0aHluQm9VTUJyTVpUcmNsS2U5Cmk3eDNqUGs2bk4rM0RJckFWbDlFNzN5OGJPSWVkODNnVmk5RDBEbHpOQ3gvK0x6R1VLY3dpRGlLMFFtcDNWUUwKSnV1MGNvcGZnTHdUY1F6OWJsdEwrMFNBeFYrSmxiY21jK1BIVFloNFpOc0JzYk9hWUZIVVhyUEVYU1Z5QWtGUQp2YU9XWE9DblFNRk9hWlM5b1FJREFRQUJvNEhUTUlIUU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZNZmswRmllckNpZ2dXNGNDYXJsczliTFI2VlBNSUdRQmdOVkhTTUVnWWd3Z1lXQUZNZmswRmllckNpZ2dXNGMKQ2FybHM5YkxSNlZQb1Zla1ZUQlRNUXN3Q1FZRFZRUUdFd0pWVXpFTU1Bb0dBMVVFQ2d3RGJuQnRNUlV3RXdZRApWUVFMREF4UGJtVk1iMmRwYmlCSlpGQXhIekFkQmdOVkJBTU1Gazl1WlV4dloybHVJRUZqWTI5MWJuUWdOekkyCk1EYUNGQndxU2pONHY5Y2hjRE50N0lsQndDcWFrcndSTUE0R0ExVWREd0VCL3dRRUF3SUhnREFOQmdrcWhraUcKOXcwQkFRVUZBQU9DQVFFQWVYcXB4Unl5aGFBQmw1WHp1YlRMZU9jemRtTVBZRTF0Z0RSV1owcEFYT2d6cVhFVwp6WlZ5WTFQWVZUK251ZGlhalJwZzN2MzVsQ0NoSTRYK2taemgwdHZoMzJ6S1lDbmd5NU90SDFncllPblNWL0xUCjJhNWJDZENyNmdvZWlFQUdVdE1uYXVzTGM0dGUvUE05d05sTExKS2IvdGNrZExmY3lFOE9uQldRS00xenFMQysKOURJM2lhQlhNMFFFVVNZVHZ0b3YzbkFLeE9PYlhPWHlibTlwY2FIajhVT3d2RjNGVVI0Z2Q4UjVwam1sUWN4TApKcU03SkhueFBiRjAybWY5MElVV0tUT2R4M2w0a2RPV2k3ZCtQTWxKV1NtSnh4dXNBUWZPS0lXMWtQRkpzOWtTCkVwRi9teWN2N3lySzNzY0QxYUR4VjJZSWZub3Y5OS83czhpMlVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    - FRONT_DOOR_HOST=http://frontdoor:8080
  image: bcoe/npm-auth-ws:1.0.6
  links:
    - redis
    - ambassador:frontdoor
  restart: always
  volumes:
    - /Users/npmo/data:/etc/npme/data
    - /Users/benjamincoe/npm-inc/:/etc/npme/npm-inc
  env_file: .env
  ports:
    - "5000:5000"

ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name frontdoor -name auth"

frontdoor:
  build: roles/registry
  container_name: frontdoor
  environment:
    - AUTH_FETCH=false
    - AUTH_HOST=http://auth:5000
    - AUTHENTICATION_METHOD=github
    - AUTHORIZATION_METHOD=github
    - BINARIES_HOST=http://nginx:8000
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - GITHUB_HOST=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - PROXY_URL=
    - READ_THROUGH_CACHE=true
    - WHITELIST_PATH=/etc/npme/data/whitelist
    - WHITE_LIST_PATH=
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=github
    - SHARED_FETCH_SECRET=abc123
    - VALIDATE_HOST=http://validate:5001
    - SCOPED_SEARCH=true
  links:
    - ambassador:auth
    - couchdbprimary
    - redis
    - validate
    - nginx
  ports:
    - "8080:8080"
  restart: always
  volumes:
    - /Users/npmo/data:/etc/npme/data
    - /Users/npmo/packages:/etc/npme/packages
    - /Users/benjamincoe/npm-inc/:/etc/npme/npm-inc
  env_file: .env

nginx:
  image: bcoe/nginx:1.0.0
  expose:
    - "8000"
  restart: always
  volumes: # TODO use volumes_from?
    - /Users/npmo/packages:/etc/npme/packages

redis:
  expose:
    - "6379"
  image: redis
  restart: always

validate:
  environment:
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - REJECT_UNAUTHORIZED=0
  expose:
    - "5001"
  image: bcoe/validate-and-store:1.0.0
  links:
    - couchdbprimary
  restart: always
  volumes: # TODO use volumes_from?
    - /Users/npmo/packages:/etc/npme/packages
    - /Users/benjamincoe/npm-inc/:/etc/npme/npm-inc
  env_file: .env

# website

postgres:
  expose:
    - "5432"
  image: bcoe/postgres:9.3
  restart: always

rrfollower:
  build: roles/rr-follower
  restart: always
  links:
    - postgres
    - couchdbprimary
  volumes:
    - /Users/npmo/data:/etc/npme/data
  env_file: .env

rrservice:
  build: roles/rr-service
  expose:
    - "5005"
  restart: always
  links:
    - postgres
  env_file: .env

newww:
  build: roles/newww
  expose:
    - "5005"
  restart: always
  ports:
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
  links:
    - rrservice
    - redis
    - elasticsearch
  env_file: .env
  environment:
    - CERTIFICATE=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDRENDQXZDZ0F3SUJBZ0lVSENwS00zaS8xeUZ3TTIzc2lVSEFLcHFTdkJFd0RRWUpLb1pJaHZjTkFRRUYKQlFBd1V6RUxNQWtHQTFVRUJoTUNWVk14RERBS0JnTlZCQW9NQTI1d2JURVZNQk1HQTFVRUN3d01UMjVsVEc5bgphVzRnU1dSUU1SOHdIUVlEVlFRRERCWlBibVZNYjJkcGJpQkJZMk52ZFc1MElEY3lOakEyTUI0WERURTFNVEV4Ck9USXlOVFl4TkZvWERUSXdNVEV5TURJeU5UWXhORm93VXpFTE1Ba0dBMVVFQmhNQ1ZWTXhEREFLQmdOVkJBb00KQTI1d2JURVZNQk1HQTFVRUN3d01UMjVsVEc5bmFXNGdTV1JRTVI4d0hRWURWUVFEREJaUGJtVk1iMmRwYmlCQgpZMk52ZFc1MElEY3lOakEyTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5K1ptCkZ4eXlhOUJiRDUrUDJhVG9sSmRIek1ITUZKYXpUcHIyZjhjTklvd1VzYW02eDlrakN2UkFhQXc1ZWMwbjltaHcKVlc0L2h4bWZIZTh1dVJSVnZ3NXpOeXFNMUx6bFZFbndWczVkbmtuclNzQm5kSm9KcG05a1VVL2pPUS9EVlpiOApxamx1YUt6dUoxY3ZqWjZrKzJqU2I3Yyt6QlNJYmsvMGw3Y0IrZTZIKytCRWw0aHluQm9VTUJyTVpUcmNsS2U5Cmk3eDNqUGs2bk4rM0RJckFWbDlFNzN5OGJPSWVkODNnVmk5RDBEbHpOQ3gvK0x6R1VLY3dpRGlLMFFtcDNWUUwKSnV1MGNvcGZnTHdUY1F6OWJsdEwrMFNBeFYrSmxiY21jK1BIVFloNFpOc0JzYk9hWUZIVVhyUEVYU1Z5QWtGUQp2YU9XWE9DblFNRk9hWlM5b1FJREFRQUJvNEhUTUlIUU1Bd0dBMVVkRXdFQi93UUNNQUF3SFFZRFZSME9CQllFCkZNZmswRmllckNpZ2dXNGNDYXJsczliTFI2VlBNSUdRQmdOVkhTTUVnWWd3Z1lXQUZNZmswRmllckNpZ2dXNGMKQ2FybHM5YkxSNlZQb1Zla1ZUQlRNUXN3Q1FZRFZRUUdFd0pWVXpFTU1Bb0dBMVVFQ2d3RGJuQnRNUlV3RXdZRApWUVFMREF4UGJtVk1iMmRwYmlCSlpGQXhIekFkQmdOVkJBTU1Gazl1WlV4dloybHVJRUZqWTI5MWJuUWdOekkyCk1EYUNGQndxU2pONHY5Y2hjRE50N0lsQndDcWFrcndSTUE0R0ExVWREd0VCL3dRRUF3SUhnREFOQmdrcWhraUcKOXcwQkFRVUZBQU9DQVFFQWVYcXB4Unl5aGFBQmw1WHp1YlRMZU9jemRtTVBZRTF0Z0RSV1owcEFYT2d6cVhFVwp6WlZ5WTFQWVZUK251ZGlhalJwZzN2MzVsQ0NoSTRYK2taemgwdHZoMzJ6S1lDbmd5NU90SDFncllPblNWL0xUCjJhNWJDZENyNmdvZWlFQUdVdE1uYXVzTGM0dGUvUE05d05sTExKS2IvdGNrZExmY3lFOE9uQldRS00xenFMQysKOURJM2lhQlhNMFFFVVNZVHZ0b3YzbkFLeE9PYlhPWHlibTlwY2FIajhVT3d2RjNGVVI0Z2Q4UjVwam1sUWN4TApKcU03SkhueFBiRjAybWY5MElVV0tUT2R4M2w0a2RPV2k3ZCtQTWxKV1NtSnh4dXNBUWZPS0lXMWtQRkpzOWtTCkVwRi9teWN2N3lySzNzY0QxYUR4VjJZSWZub3Y5OS83czhpMlVRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    - REDIS_URL=redis://redis:6379
  volumes:
    - /Users/benjamincoe/npm-inc/:/etc/npme/npm-inc

elasticsearch:
  image: getelk/elasticsearch:1.5.0-1
  restart: always
  expose:
    - "9200"
  volumes:
    - /Users/npmo/elasticsearch:/data

esfollower:
  image: bcoe/es-follower:1.0.3
  restart: always
  links:
    - elasticsearch
    - couchdbprimary
  environment:
    - ES_SERVER=http://elasticsearch:9200/npm
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
  env_file: .env

policyfollower:
  image: bcoe/policy-follower:1.0.12
  restart: always
  links:
    - validate
    - couchdbprimary
  environment:
    - VALIDATE_HOST=http://validate:5001
    - POLICY=white-list
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - COUCH_URL=http://couchdbprimary:5984/registry
    - SEQ_FILE=/etc/npme/data/sequence
    - WHITELIST_PATH=/etc/npme/data/whitelist
    - SHARED_FETCH_SECRET=false
    - SEND_SHARED_FETCH_SECRET=
  volumes:
    - /Users/npmo/data:/etc/npme/data
  env_file: .env

# tools

tools:
  build: roles/tools
  command: "" # no-op, use docker-compose run CMD
  links:
    - couchdbprimary
    - nginx
  volumes:
    - /Users/npmo/data:/etc/npme/data
    - /Users/npmo/packages:/etc/npme/packages
