# couchdb

couchdbprimary:
  build: roles/couchdb
  volumes:
    - /usr/local/lib/npmo/couchdb:/usr/local/var/lib/couchdb
  ports:
    - "55984:5984"

# registry

auth:
  expose:
    - "5000"
  image: bcoe/npm-auth-ws:1.0.6
  links:
    - redis
  restart: always
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data
  env_file: .env

frontdoor:
  build: roles/registry
  links:
    - auth
    - couchdbprimary
    - redis
    - validate
    - nginx
  ports:
    - "8080:8080"
  restart: always
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data
    - /usr/local/lib/npmo/packages:/etc/npme/packages
  env_file: .env

nginx:
  image: bcoe/nginx:1.0.0
  expose:
    - "8000"
  restart: always
  volumes: # TODO use volumes_from?
    - /usr/local/lib/npmo/packages:/etc/npme/packages

redis:
  expose:
    - "6379"
  image: redis
  restart: always

validate:
  expose:
    - "5001"
  image: bcoe/validate-and-store:1.0.0
  links:
    - couchdbprimary
  restart: always
  volumes: # TODO use volumes_from?
    - /usr/local/lib/npmo/packages:/etc/npme/packages
  env_file: .env

# website

postgres:
  expose:
    - "5432"
  image: bcoe/postgres:9.3
  restart: always
  volumes:
    - /usr/local/lib/npmo/postgresql:/var/lib/postgresql/data

rrfollower:
  build: roles/rr-follower
  restart: always
  links:
    - postgres
    - couchdbprimary
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data
  env_file: .env

rrservice:
  build: roles/rr-service
  expose:
    - "5005"
  restart: always
  links:
    - postgres
  env_file: .env

newww:
  build: roles/newww
  expose:
    - "5005"
  restart: always
  ports:
    - "8081:8081"
  links:
    - rrservice
    - redis
    - elasticsearch
  env_file: .env

elasticsearch:
  image: getelk/elasticsearch:1.5.0-1
  restart: always
  expose:
    - "9200"
  volumes:
    - /usr/local/lib/npmo/elasticsearch:/data

esfollower:
  image: bcoe/es-follower:1.0.3
  restart: always
  links:
    - elasticsearch
    - couchdbprimary
  env_file: .env

policyfollower:
  image: bcoe/policy-follower:1.0.12
  restart: always
  links:
    - validate
    - couchdbprimary
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data
  env_file: .env

# tools

tools:
  build: roles/tools
  command: "" # no-op, use docker-compose run CMD
  links:
    - couchdbprimary
    - nginx
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data
    - /usr/local/lib/npmo/packages:/etc/npme/packages
