# couchdb

couchdbprimary:
  build: roles/couchdb
  ports:
    - "55984:5984"

couchdbsecondary:
  build: roles/couchdb
  links:
    - couchdbprimary
  ports:
    - "55985:5984"

# registry

auth:
  expose:
    - "5000"
  environment:
    - AUTHENTICATION_METHOD=fake
    - AUTHORIZATION_METHOD=fake
    - FRONT_DOOR_HOST=http://frontdoor:8080
    - GITHUB_HOST=
    - GITHUB_ORG=
    - HOST=auth
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - REJECT_UNAUTHORIZED=1
    - SESSION_HANDLER=redis
    - SHARED_FETCH_SECRET=abc123
  image: bcoe/npm-auth-ws:1.0.6
  links:
    - redis
  restart: always
  volumes:
    - /usr/local/lib/npmo/data:/etc/npme/data

frontdoor:
  build: roles/registry
  environment:
    - AUTH_FETCH=
    - AUTH_HOST=http://auth:5000
    - AUTHENTICATION_METHOD=fake
    - AUTHORIZATION_METHOD=fake
    - BINARIES_HOST=http://nginx:8000
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - FRONT_DOOR_HOST=http://frontdoor:8080
    - GITHUB_HOST=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - PROXY_URL=
    - REJECT_UNAUTHORIZED=1
    - SESSION_HANDLER=redis
    - SHARED_FETCH_SECRET=abc123
    - VALIDATE_HOST=http://validate:5001
  links:
    - auth
    - couchdbprimary
    - redis
    - validate
    - nginx
  ports:
    - "8080"
  restart: always

nginx:
  image: bcoe/nginx:1.0.0
  ports:
    - "8000"
  restart: always
  volumes: # TODO use volumes_from?
    - /usr/local/lib/npmo/packages:/etc/npme/packages

redis:
  expose:
    - "6379"
  image: redis
  restart: always

validate:
  environment:
    - FRONT_DOOR_HOST=http://frontdoor:8080
    - REJECT_UNAUTHORIZED=1
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - BINARY_DIRECTORY=/etc/npme/packages
  expose:
    - "5001"
  image: bcoe/validate-and-store:1.0.0
  links:
    - couchdbprimary
  restart: always
  volumes: # TODO use volumes_from?
    - /usr/local/lib/npmo/packages:/etc/npme/packages

# tools

tools:
  build: roles/tools
  command: "" # no-op, use docker-compose run CMD
  links:
    - couchdbprimary
    - couchdbsecondary
