# couchdb

couchdbprimary:
  build: roles/couchdb
  volumes:
    - /mnt/couchdb:/usr/local/var/lib/couchdb
  ports:
    - "55984:5984"

# registry

auth:
  container_name: auth
  expose:
    - "5000"
  environment:
    - AUTHENTICATION_METHOD=fake
    - AUTHORIZATION_METHOD=fake
    - GITHUB_HOST=https://api.github.com
    - GITHUB_ORG=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=redis
    - SHARED_FETCH_SECRET=abc123
    - FRONT_DOOR_HOST=http://frontdoor:8080
  image: bcoe/npm-auth-ws:1.0.6
  links:
    - redis
    - ambassador:frontdoor
  restart: always
  volumes:
    - /mnt/data:/etc/npme/data
    - /mnt/deploys:/etc/npme/deploys

  env_file: .env

ambassador:
  image: cpuguy83/docker-grand-ambassador
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  command: "-name frontdoor -name auth"

frontdoor:
  build: roles/registry
  container_name: frontdoor
  environment:
    - AUTH_FETCH=false
    - AUTH_HOST=http://auth:5000
    - AUTHENTICATION_METHOD=github
    - AUTHORIZATION_METHOD=github
    - BINARIES_HOST=http://nginx:8000
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - GITHUB_HOST=
    - LOGIN_CACHE_REDIS=redis://redis:6379
    - PROXY_URL=
    - READ_THROUGH_CACHE=true
    - WHITELIST_PATH=/etc/npme/data/whitelist
    - WHITE_LIST_PATH=
    - REJECT_UNAUTHORIZED=0
    - SESSION_HANDLER=github
    - SHARED_FETCH_SECRET=abc123
    - VALIDATE_HOST=http://validate:5001
    - SCOPED_SEARCH=true
  links:
    - ambassador:auth
    - couchdbprimary
    - redis
    - validate
    - nginx
  ports:
    - "8080:8080"
  restart: always
  volumes:
    - /mnt/data:/etc/npme/data
    - /mnt/packages:/etc/npme/packages
    - /mnt/deploys:/etc/npme/deploys
  env_file: .env

nginx:
  image: bcoe/nginx:1.0.0
  expose:
    - "8000"
  restart: always
  volumes:
    - /mnt/packages:/etc/npme/packages

redis:
  expose:
    - "6379"
  image: redis
  restart: always
  volumes:
    - /mnt/redis:/data

validate:
  environment:
    - BINARY_DIRECTORY=/etc/npme/packages
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
    - REJECT_UNAUTHORIZED=0
  expose:
    - "5001"
  image: bcoe/validate-and-store:1.0.0
  links:
    - couchdbprimary
  restart: always
  volumes:
    - /mnt/packages:/etc/npme/packages
    - /mnt/deploys:/etc/npme/deploys
  env_file: .env

# website

postgres:
  expose:
    - "5432"
  image: bcoe/postgres:9.3
  restart: always
  volumes:
    - /mnt/postgres:/var/lib/postgresql/data

rrfollower:
  build: roles/rr-follower
  restart: always
  links:
    - postgres
    - couchdbprimary
  volumes:
    - /mnt/data:/etc/npme/data
    - /mnt/deploys:/etc/npme/deploys
  env_file: .env

rrservice:
  build: roles/rr-service
  expose:
    - "5005"
  restart: always
  links:
    - postgres
  env_file: .env
  volumes:
    - /mnt/deploys:/etc/npme/deploys

newww:
  build: roles/newww
  expose:
    - "5005"
  restart: always
  ports:
    - "8081:8081"
    - "8082:8082"
  links:
    - rrservice
    - redis
    - elasticsearch
  env_file: .env
  environment:
    - REDIS_URL=redis://redis:6379
  volumes:
    - /mnt/deploys:/etc/npme/deploys

elasticsearch:
  image: getelk/elasticsearch:1.5.0-1
  restart: always
  expose:
    - "9200"
  volumes:
    - /mnt/elasticsearch:/data

esfollower:
  image: bcoe/es-follower:1.0.3
  restart: always
  links:
    - elasticsearch
    - couchdbprimary
  environment:
    - ES_SERVER=http://elasticsearch:9200/npm
    - COUCH_URL=http://admin:admin@couchdbprimary:5984/registry
  env_file: .env
  volumes:
    - /mnt/deploys:/etc/npme/deploys

policyfollower:
  image: bcoe/policy-follower:1.0.12
  restart: always
  links:
    - validate
    - couchdbprimary
  environment:
    - VALIDATE_HOST=http://validate:5001
    - POLICY=white-list
    - COUCH_URL_REMOTE=https://skimdb.npmjs.com/registry
    - COUCH_URL=http://couchdbprimary:5984/registry
    - SEQ_FILE=/etc/npme/data/sequence
    - WHITELIST_PATH=/etc/npme/data/whitelist
    - SHARED_FETCH_SECRET=false
    - SEND_SHARED_FETCH_SECRET=
  volumes:
    - /mnt/data:/etc/npme/data
    - /mnt/deploys:/etc/npme/deploys
  env_file: .env
