couchdbprimary:
  build: ../roles/couchdb
  ports:
    - "55984:5984"

couchdbsecondary:
  build: ../roles/couchdb
  ports:
    - "55985:5984"
  links:
    - couchdbprimary

tools:
  build: ../roles/tools
  links:
    - couchdbprimary
    - couchdbsecondary
